custom:
  enable_rule_generator: false
  overwrite_original_rules: false

  clash_rule_base: https://raw.githubusercontent.com/bemarkt/scripts/master/provider/config/subconverter/all-base.tpl
  surge_rule_base: https://raw.githubusercontent.com/bemarkt/scripts/master/provider/config/subconverter/all-base.tpl
  surfboard_rule_base: https://raw.githubusercontent.com/bemarkt/scripts/master/provider/config/subconverter/all-base.tpl
  mellow_rule_base: https://raw.githubusercontent.com/bemarkt/scripts/master/provider/config/subconverter/all-base.tpl
  quan_rule_base: https://raw.githubusercontent.com/bemarkt/scripts/master/provider/config/subconverter/all-base.tpl
  quanx_rule_base: https://raw.githubusercontent.com/bemarkt/scripts/master/provider/config/subconverter/all-base.tpl
  loon_rule_base: https://raw.githubusercontent.com/bemarkt/scripts/master/provider/config/subconverter/all-base.tpl
  sssub_rule_base: https://raw.githubusercontent.com/bemarkt/scripts/master/provider/config/subconverter/all-base.tpl

  exclude_remarks:
    - "(å‰©ä½™æµé‡|åˆ°æœŸæ—¶é—´|è¿‡æœŸæ—¶é—´|å®˜ç½‘|äº§å“åç§°|å…ˆè´­ä¹°å¥—é¤|æµé‡æ¶ˆè€—|å”¯ä¸€å®˜ç½‘|æ›´æ–°è®¢é˜…|æœ¬ç«™)"
    - "(.*æµé‡.*å‰©.*å¤©)"
    - "(â– ç­‰çº§è­¦æŠ¥â– )"
    - "(è¿‘æœŸä¸‹çº¿|æš‚æ—¶ä¸‹æ¶)"
    - "(ç²¾ç®€)"

  rename_node:
    - { match: "å•†å®½", replace: "" }
    - { match: "ç§»åŠ¨", replace: "CM" }
    - { match: "ç”µä¿¡", replace: "CT" }
    - { match: "è”é€š", replace: "CU" }
    - { match: "ä¸Šæµ·", replace: "æ²ª" }
    - { match: "ä¸­å›½", replace: "ä¸­" }
    - { match: "äº‘å—", replace: "äº‘" }
    - { match: "ä½›å±±", replace: "ç¦…" }
    - { match: "åŒ—äº¬", replace: "äº¬" }
    - { match: "å—äº¬", replace: "å®" }
    - { match: "å—é˜³", replace: "å®›" }
    - { match: "å››å·", replace: "å·" }
    - { match: "å¤©æ´¥", replace: "æ´¥" }
    - { match: "å®æ³¢", replace: "ç”¬" }
    - { match: "å®‰å¾½", replace: "çš–" }
    - { match: "å¹¿ä¸œ", replace: "ç²¤" }
    - { match: "å¹¿å·", replace: "ç©—" }
    - { match: "å¾å·", replace: "å¾" }
    - { match: "æˆéƒ½", replace: "è“‰" }
    - { match: "æ­å·", replace: "æ­" }
    - { match: "æ­¦æ±‰", replace: "æ±‰" }
    - { match: "æ±•å¤´", replace: "æ±•" }
    - { match: "æ±Ÿè‹", replace: "è‹" }
    - { match: "æ²ˆé˜³", replace: "æ²ˆ" }
    - { match: "æµ™æ±Ÿ", replace: "æµ™" }
    - { match: "æµ·å—", replace: "ç¼" }
    - { match: "æ·±åœ³", replace: "æ·±" }
    - { match: "æ¹–åŒ—", replace: "é„‚" }
    - { match: "æ¹–å—", replace: "æ¹˜" }
    - { match: "é•¿æ²™", replace: "é•¿" }
    - { match: "ç æµ·", replace: "ç " }
    - { match: "ç¦å»º", replace: "é—½" }
    - { match: "ç‘å£«", replace: "ç‘" }
    - { match: "è®¸æ˜Œ", replace: "è®¸" }
    - { match: "è´µå·", replace: "è´µ" }
    - { match: "è´µé˜³", replace: "ç­‘" }
    - { match: "è¶Šå—", replace: "è¶Š" }
    - { match: "é•‡æ±Ÿ", replace: "é•‡" }
    - { match: "é’å²›", replace: "é’" }
    - { match: "é’æµ·", replace: "é’" }
    - { match: "é¦™æ¸¯", replace: "æ¸¯" }
    - { match: "æ·±æ¸¯ä¸“çº¿", replace: "æ·±æ¸¯" }
    - { match: "æ¾³é—¨", replace: "æ¾³" }
    - { match: "å°æ¹¾", replace: "å°" }
    - { match: "æ—¥æœ¬", replace: "æ—¥" }
    - { match: "æ–°åŠ å¡", replace: "æ–°" }
    - { match: "éŸ©å›½", replace: "éŸ©" }
    - { match: "ç¾å›½", replace: "ç¾" }
    - { match: "ä¿„ç½—æ–¯", replace: "ä¿„" }
    - { match: "åŠ æ‹¿å¤§", replace: "åŠ " }
    - { match: "å°åº¦", replace: "å°" }
    - { match: "é©¬å“ˆæ‹‰æ–½ç‰¹æ‹‰", replace: "å­Ÿä¹°" }
    - { match: "èŠ¬å…°", replace: "èŠ¬" }
    - { match: "è‹±å›½", replace: "è‹±" }
    - { match: "æ³•å›½", replace: "æ³•" }
    - { match: "åœŸè€³å…¶", replace: "åœŸ" }
    - { match: "å¾·å›½", replace: "å¾·" }
    - { match: "æ„å¤§åˆ©", replace: "æ„" }
    - { match: "æ³°å›½", replace: "æ³°" }
    - { match: "è²å¾‹å®¾", replace: "è²" }
    - { match: "(-)", replace: "â–·" }
    - { match: "(A|B|C|D)(\s)?(\d\d)", replace: "$3" }
    - { match: '(.*)(\[)(å€ç‡:)(.*[0-9])(\])', replace: "$1[x$4]" }
    - { match: '(\[x.*[0-9]\])(.*)', replace: "$2$1" }
    - { match: " ", replace: "" }
    - { match: "[ ]", replace: "" }
    - { match: "( )", replace: "" }
  proxy_groups:
    # AIäº‘å¯ç”¨èŠ‚ç‚¹
    - name: "ğŸ”„ AIäº‘å¯è¾¾"
      type: fallback
      rule:
        [
          "[]ğŸ‡­ğŸ‡° é¦™æ¸¯ | Too Naive",
          "[]ğŸ‡¨ğŸ‡³ å°æ¹¾ | ä½ å¥½æœºè½¦å“¦",
          "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬ | ç¥ç½—å¤©å¾",
          "[]ğŸ‡°ğŸ‡· éŸ©å›½ | æ¥è‡ªæ˜Ÿæ˜Ÿçš„ä½ ",
          "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ | ç»€é’ä¹‹æ‹³",
          "[]ğŸ‡ºğŸ‡² ç¾å›½ | æ¢ç´¢è€…å·",
          "[]ğŸ—ºï¸ å…¶ä»– | å‰©ä½™ä»·å€¼",
        ]
      url: "http://www.gstatic.com/generate_204"
      interval: 180
      timeout: 5
      tolerance: 50
    # ä»£ç†èŠ‚ç‚¹é€‰æ‹©
    - name: "â›µ ç›´æŒ‚äº‘å¸†æµæ²§æµ·"
      type: select
      rule:
        [
          "[]ğŸ‡­ğŸ‡° é¦™æ¸¯ | Too Naive",
          "[]ğŸ‡¨ğŸ‡³ å°æ¹¾ | ä½ å¥½æœºè½¦å“¦",
          "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬ | ç¥ç½—å¤©å¾",
          "[]ğŸ‡°ğŸ‡· éŸ©å›½ | æ¥è‡ªæ˜Ÿæ˜Ÿçš„ä½ ",
          "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ | ç»€é’ä¹‹æ‹³",
          "[]ğŸ‡ºğŸ‡² ç¾å›½ | æ¢ç´¢è€…å·",
          "[]ğŸ—ºï¸ å…¶ä»– | å‰©ä½™ä»·å€¼",
          "[]ğŸ”„ AIäº‘å¯è¾¾",
          "[]ğŸ  é”¦åŸè™½äº‘ä¹ï¼Œä¸å¦‚æ—©è¿˜å®¶",
        ]
    # å›½å†…ç½‘ç«™
    - name: "ğŸš£ é•¿é£ç ´æµªä¼šæœ‰æ—¶"
      type: select
      rule: ["[]ğŸ  é”¦åŸè™½äº‘ä¹ï¼Œä¸å¦‚æ—©è¿˜å®¶", "[]â›µ ç›´æŒ‚äº‘å¸†æµæ²§æµ·"]
    # å¤§é™†æµåª’ä½“é¢å‘æ¸¯æ¾³å°é™å®šæœåŠ¡
    - name: "ğŸŒ å›½å†…åª’ä½“"
      type: select
      rule:
        [
          "[]ğŸš£ é•¿é£ç ´æµªä¼šæœ‰æ—¶",
          "[]ğŸ‡­ğŸ‡° é¦™æ¸¯ | Too Naive",
          "[]ğŸ‡¨ğŸ‡³ å°æ¹¾ | ä½ å¥½æœºè½¦å“¦",
          "[]â›µ ç›´æŒ‚äº‘å¸†æµæ²§æµ·",
        ]
    - name: "ğŸ’ƒTik Tok"
      type: select
      rule:
        [
          "[]â›µ ç›´æŒ‚äº‘å¸†æµæ²§æµ·",
          "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ | ç»€é’ä¹‹æ‹³",
          "[]ğŸ‡­ğŸ‡° é¦™æ¸¯ | Too Naive",
          "[]ğŸ‡¨ğŸ‡³ å°æ¹¾ | ä½ å¥½æœºè½¦å“¦",
          "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬ | ç¥ç½—å¤©å¾",
          "[]ğŸ‡°ğŸ‡· éŸ©å›½ | æ¥è‡ªæ˜Ÿæ˜Ÿçš„ä½ ",
          "[]ğŸ‡ºğŸ‡² ç¾å›½ | æ¢ç´¢è€…å·",
          "[]ğŸ—ºï¸ å…¶ä»– | å‰©ä½™ä»·å€¼",
        ]
    # å›½é™…é«˜é›…éŸ³ä¹å¹³å°
    - name: "ğŸµ é«˜é›…éŸ³ä¹"
      type: select
      rule:
        [
          "[]â›µ ç›´æŒ‚äº‘å¸†æµæ²§æµ·",
          "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ | ç»€é’ä¹‹æ‹³",
          "[]ğŸ‡­ğŸ‡° é¦™æ¸¯ | Too Naive",
          "[]ğŸ‡¨ğŸ‡³ å°æ¹¾ | ä½ å¥½æœºè½¦å“¦",
          "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬ | ç¥ç½—å¤©å¾",
          "[]ğŸ‡°ğŸ‡· éŸ©å›½ | æ¥è‡ªæ˜Ÿæ˜Ÿçš„ä½ ",
          "[]ğŸ‡ºğŸ‡² ç¾å›½ | æ¢ç´¢è€…å·",
          "[]ğŸ—ºï¸ å…¶ä»– | å‰©ä½™ä»·å€¼",
        ]
    # å›½å¤–æµåª’ä½“è§£é”
    - name: "ğŸï¸ æµåª’ä½“"
      type: select
      rule:
        [
          "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ | ç»€é’ä¹‹æ‹³",
          "[]ğŸ‡­ğŸ‡° é¦™æ¸¯ | Too Naive",
          "[]ğŸ‡¨ğŸ‡³ å°æ¹¾ | ä½ å¥½æœºè½¦å“¦",
          "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬ | ç¥ç½—å¤©å¾",
          "[]ğŸ‡°ğŸ‡· éŸ©å›½ | æ¥è‡ªæ˜Ÿæ˜Ÿçš„ä½ ",
          "[]ğŸ‡ºğŸ‡² ç¾å›½ | æ¢ç´¢è€…å·",
          "[]ğŸ—ºï¸ å…¶ä»– | å‰©ä½™ä»·å€¼",
          "[]â›µ ç›´æŒ‚äº‘å¸†æµæ²§æµ·",
        ]
    # å›½é™…åª’ä½“æœåŠ¡
    - name: "ğŸŒ å›½é™…åª’ä½“"
      type: select
      rule:
        [
          "[]â›µ ç›´æŒ‚äº‘å¸†æµæ²§æµ·",
          "[]ğŸ”„ AIäº‘å¯è¾¾",
          "[]ğŸ‡­ğŸ‡° é¦™æ¸¯ | Too Naive",
          "[]ğŸ‡¨ğŸ‡³ å°æ¹¾ | ä½ å¥½æœºè½¦å“¦",
          "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬ | ç¥ç½—å¤©å¾",
          "[]ğŸ‡°ğŸ‡· éŸ©å›½ | æ¥è‡ªæ˜Ÿæ˜Ÿçš„ä½ ",
          "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ | ç»€é’ä¹‹æ‹³",
          "[]ğŸ‡ºğŸ‡² ç¾å›½ | æ¢ç´¢è€…å·",
          "[]ğŸ—ºï¸ å…¶ä»– | å‰©ä½™ä»·å€¼",
        ]
    # é’å£®å¹´æœåŠ¡
    - name: "ğŸ’ª é’å£®å¹´æ¨¡å¼"
      type: select
      rule:
        [
          "[]â›µ ç›´æŒ‚äº‘å¸†æµæ²§æµ·",
          "[]ğŸš£ é•¿é£ç ´æµªä¼šæœ‰æ—¶",
          "[]ğŸ‡­ğŸ‡° é¦™æ¸¯ | Too Naive",
          "[]ğŸ‡¨ğŸ‡³ å°æ¹¾ | ä½ å¥½æœºè½¦å“¦",
          "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬ | ç¥ç½—å¤©å¾",
          "[]ğŸ‡°ğŸ‡· éŸ©å›½ | æ¥è‡ªæ˜Ÿæ˜Ÿçš„ä½ ",
          "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ | ç»€é’ä¹‹æ‹³",
          "[]ğŸ‡ºğŸ‡² ç¾å›½ | æ¢ç´¢è€…å·",
          "[]ğŸ—ºï¸ å…¶ä»– | å‰©ä½™ä»·å€¼",
        ]
    # Developer å¼€å‘è€…æœåŠ¡
    - name: "ğŸ‘¨â€ğŸ’» å¼€å‘è€…æœåŠ¡"
      type: select
      rule: ["[]â›µ ç›´æŒ‚äº‘å¸†æµæ²§æµ·", "[]ğŸš£ é•¿é£ç ´æµªä¼šæœ‰æ—¶"]
    # Scholar å­¦æœ¯æœåŠ¡
    - name: "ğŸ‘¨â€ğŸ”¬ å­¦æœ¯æœåŠ¡"
      type: select
      rule: ["[]ğŸš£ é•¿é£ç ´æµªä¼šæœ‰æ—¶", "[]â›µ ç›´æŒ‚äº‘å¸†æµæ²§æµ·"]
    # Samsung æœåŠ¡ä»£ç†
    - name: "âœ¨ ä¸‰æ˜ŸæœåŠ¡"
      type: select
      rule: ["[]ğŸš£ é•¿é£ç ´æµªä¼šæœ‰æ—¶", "[]â›µ ç›´æŒ‚äº‘å¸†æµæ²§æµ·"]
    # Apple æœåŠ¡ä»£ç†
    - name: "ğŸ è‹¹æœæœåŠ¡"
      type: select
      rule: ["[]ğŸš£ é•¿é£ç ´æµªä¼šæœ‰æ—¶", "[]â›µ ç›´æŒ‚äº‘å¸†æµæ²§æµ·"]
    # Microsoft æœåŠ¡ä»£ç†
    - name: "â“‚ï¸ å¾®è½¯æœåŠ¡"
      type: select
      rule: ["[]ğŸš£ é•¿é£ç ´æµªä¼šæœ‰æ—¶", "[]â›µ ç›´æŒ‚äº‘å¸†æµæ²§æµ·"]
    # SpeedTest æµ‹é€Ÿ
    - name: "â±ï¸ æµ‹é€ŸæœåŠ¡"
      type: select
      rule: ["[]ğŸš£ é•¿é£ç ´æµªä¼šæœ‰æ—¶", "[]â›µ ç›´æŒ‚äº‘å¸†æµæ²§æµ·"]
    # å¹¿å‘Šæ‹¦æˆª
    - name: "ğŸš§ é€šç”¨æ‹¦æˆª"
      type: select
      rule: ["[]ğŸˆ² ä¸€å¤«å½“å…³ï¼Œä¸‡å¤«è«å¼€", "[]ğŸ  é”¦åŸè™½äº‘ä¹ï¼Œä¸å¦‚æ—©è¿˜å®¶"]
    - name: "ğŸƒ åº”ç”¨å‡€åŒ–"
      type: select
      rule:
        [
          "[]ğŸš§ é€šç”¨æ‹¦æˆª",
          "[]ğŸˆ² ä¸€å¤«å½“å…³ï¼Œä¸‡å¤«è«å¼€",
          "[]ğŸ  é”¦åŸè™½äº‘ä¹ï¼Œä¸å¦‚æ—©è¿˜å®¶",
        ]
    # ç§ã®DIY
    - name: "ğŸ‡­ğŸ‡° é¦™æ¸¯ | Too Naive"
      type: select
      rule:
        [
          "[]ğŸ‡­ğŸ‡° é¦™æ¸¯ | ä¸¥é€‰",
          "[]ğŸ‡­ğŸ‡° æ·±æ¸¯ä¸“çº¿",
          "[]ğŸ‡­ğŸ‡° é¦™æ¸¯ | è‡ªé€‰",
          "[]ğŸ‡­ğŸ‡° é¦™æ¸¯ | è½®è¯¢",
        ]
    - name: "ğŸ‡­ğŸ‡° é¦™æ¸¯ | ä¸¥é€‰"
      type: url-test
      rule: ["!!PROVIDER=HK"]
      url: "http://www.gstatic.com/generate_204"
      interval: 180
      timeout: 5
      tolerance: 50
    - name: "ğŸ‡­ğŸ‡° é¦™æ¸¯ | è½®è¯¢"
      type: fallback
      rule: ["!!PROVIDER=HK"]
      url: "http://www.gstatic.com/generate_204"
      interval: 180
      timeout: 5
      tolerance: 50
    - name: "ğŸ‡­ğŸ‡° é¦™æ¸¯ | è‡ªé€‰"
      type: select
      rule: ["!!PROVIDER=HK"]
      url: "http://www.gstatic.com/generate_204"
      interval: 180
      timeout: 5
      tolerance: 50
    - name: "ğŸ‡­ğŸ‡° æ·±æ¸¯ä¸“çº¿"
      type: url-test
      rule: ["!!PROVIDER=S-HK"]
      url: "http://www.gstatic.com/generate_204"
      interval: 180
      timeout: 5
      tolerance: 50
    - name: "ğŸ‡¨ğŸ‡³ å°æ¹¾ | ä½ å¥½æœºè½¦å“¦"
      type: url-test
      rule: ["!!PROVIDER=TW"]
      url: "http://www.gstatic.com/generate_204"
      interval: 180
      timeout: 5
      tolerance: 50
    - name: "ğŸ‡¯ğŸ‡µ æ—¥æœ¬ | ç¥ç½—å¤©å¾"
      type: url-test
      rule: ["!!PROVIDER=JP"]
      url: "http://www.gstatic.com/generate_204"
      interval: 180
      timeout: 5
      tolerance: 50
    - name: "ğŸ‡°ğŸ‡· éŸ©å›½ | æ¥è‡ªæ˜Ÿæ˜Ÿçš„ä½ "
      type: url-test
      rule: ["!!PROVIDER=KR"]
      url: "http://www.gstatic.com/generate_204"
      interval: 180
      timeout: 5
      tolerance: 50
    - name: "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ | ç»€é’ä¹‹æ‹³"
      type: url-test
      rule: ["!!PROVIDER=SG"]
      url: "http://www.gstatic.com/generate_204"
      interval: 180
      timeout: 5
      tolerance: 50
    - name: "ğŸ‡ºğŸ‡² ç¾å›½ | æ¢ç´¢è€…å·"
      type: url-test
      rule: ["!!PROVIDER=US"]
      url: "http://www.gstatic.com/generate_204"
      interval: 180
      timeout: 5
      tolerance: 50
    - name: "ğŸ—ºï¸ å…¶ä»– | å‰©ä½™ä»·å€¼"
      type: select
      rule: ["!!PROVIDER=Other"]
    # ä½ ä»¥ä¸ºä½ èƒ½è·‘ï¼Ÿ
    - name: "ğŸ•¸ï¸ æ¼ç½‘ä¹‹é±¼"
      type: select
      rule: ["[]â›µ ç›´æŒ‚äº‘å¸†æµæ²§æµ·", "[]ğŸš£ é•¿é£ç ´æµªä¼šæœ‰æ—¶"]
    - name: "ğŸ  é”¦åŸè™½äº‘ä¹ï¼Œä¸å¦‚æ—©è¿˜å®¶"
      type: select
      rule: ["[]DIRECT"]
    - name: "ğŸˆ² ä¸€å¤«å½“å…³ï¼Œä¸‡å¤«è«å¼€"
      type: select
      rule: ["[]REJECT"]

  add_emoji: true
  remove_old_emoji: true
  emojis:
    - { match: "(?i:Bandwidth|expire|æµé‡|æ—¶é—´|åº”æ€¥|è¿‡æœŸ)", emoji: "ğŸ³ï¸â€ğŸŒˆ" }
    - { match: "(NetEaseMusic|ç½‘æ˜“äº‘éŸ³ä¹|ç½‘æ˜“äº‘è§£é”)", emoji: "ğŸ¶" }
    - { match: "(Ascension|é˜¿æ£®æ¾)", emoji: "ğŸ‡¦ğŸ‡¨" }
    - { match: "(UAE|Dubai|é˜¿è”é…‹|è¿ªæ‹œ)", emoji: "ğŸ‡¦ğŸ‡ª" }
    - { match: "(é˜¿å°”å·´å°¼äºš|Albania)", emoji: "ğŸ‡¦ğŸ‡±" }
    - { match: "(AR|é˜¿æ ¹å»·|Argentina)", emoji: "ğŸ‡¦ğŸ‡·" }
    - { match: "(Austria|Vienna|å¥¥åœ°åˆ©|ç»´ä¹Ÿçº³)", emoji: "ğŸ‡¦ğŸ‡¹" }
    - { match: "(AU|Australia|Sydney|æ¾³å¤§åˆ©äºš|æ¾³æ´²|æ‚‰å°¼)", emoji: "ğŸ‡¦ğŸ‡º" }
    - { match: "(é˜¿å¡æ‹œç–†|Azerbaijan)", emoji: "ğŸ‡¦ğŸ‡¿" }
    - {
        match: "(æ³¢é»‘å…±å’Œå›½|æ³¢å£«å°¼äºšä¸èµ«å¡å“¥ç»´çº³|Bosnia|Herzegovina)",
        emoji: "ğŸ‡§ğŸ‡¦",
      }
    - { match: "(BE|Belgium|æ¯”åˆ©æ—¶)", emoji: "ğŸ‡§ğŸ‡ª" }
    - { match: "(ä¿åŠ åˆ©äºš|Bulgaria)", emoji: "ğŸ‡§ğŸ‡¬" }
    - { match: "(BR|Brazil|Paulo|å·´è¥¿|åœ£ä¿ç½—)", emoji: "ğŸ‡§ğŸ‡·" }
    - {
        match: "(Canada|Montreal|Vancouver|åŠ æ‹¿å¤§|åŠ (?!å·|å¡).*(?!â–·|å›|è½¬)|è’™ç‰¹åˆ©å°”|æ¸©å“¥å|æ¥“è‘‰|æ«å¶|CA)",
        emoji: "ğŸ‡¨ğŸ‡¦",
      }
    - { match: "(Switzerland|Zurich|ç‘å£«|è‹é»ä¸–)", emoji: "ğŸ‡¨ğŸ‡­" }
    - { match: "(æ™ºåˆ©|Chile)", emoji: "ğŸ‡¨ğŸ‡±" }
    - { match: "(Colombia|å“¥ä¼¦æ¯”äºš)", emoji: "ğŸ‡¨ğŸ‡´" }
    - { match: "(Costa Rica|å“¥æ–¯è¾¾é»åŠ )", emoji: "ğŸ‡¨ğŸ‡·" }
    - { match: "(å¡æµ¦è·¯æ–¯|Cyprus)", emoji: "ğŸ‡¨ğŸ‡¾" }
    - { match: "(Czech|æ·å…‹)", emoji: "ğŸ‡¨ğŸ‡¿" }
    - { match: "(?i:DE|Germany|æ³•å…°å…‹ç¦|å¾·.*(?!â–·|å›|è½¬))", emoji: "ğŸ‡©ğŸ‡ª" }
    - { match: "(Denmark|ä¸¹éº¦)", emoji: "ğŸ‡©ğŸ‡°" }
    - { match: "(çˆ±æ²™å°¼äºš|Estonia)", emoji: "ğŸ‡ªğŸ‡ª" }
    - { match: "(åŸƒåŠ|Egypt)", emoji: "ğŸ‡ªğŸ‡¬" }
    - { match: "(Spain|è¥¿ç­ç‰™)", emoji: "ğŸ‡ªğŸ‡¸" }
    - { match: "(Europe|æ¬§æ´²)", emoji: "ğŸ‡ªğŸ‡º" }
    - { match: "(Finland|Helsinki|èŠ¬å…°|èµ«å°”è¾›åŸº)", emoji: "ğŸ‡«ğŸ‡®" }
    - { match: "(FR|France|Paris|æ³•å›½.*(?!â–·|å›|è½¬)|å·´é»)", emoji: "ğŸ‡«ğŸ‡·" }
    - { match: "(æ ¼é²å‰äºš|Georgia)", emoji: "ğŸ‡¬ğŸ‡ª" }
    - { match: "(å¸Œè…Š|Greece)", emoji: "ğŸ‡¬ğŸ‡·" }
    - { match: "(å…‹ç½—åœ°äºš|Croatia)", emoji: "ğŸ‡­ğŸ‡·" }
    - { match: "(Hungary|åŒˆç‰™åˆ©)", emoji: "ğŸ‡­ğŸ‡º" }
    - { match: "(Indonesia|Jakarta|å°å°¼|å°åº¦å°¼è¥¿äºš|é›…åŠ è¾¾)", emoji: "ğŸ‡®ğŸ‡©" }
    - { match: "(Ireland|Dublin|çˆ±å°”å…°|éƒ½æŸæ—)", emoji: "ğŸ‡®ğŸ‡ª" }
    - { match: "(Israel|ä»¥è‰²åˆ—)", emoji: "ğŸ‡®ğŸ‡±" }
    - { match: "(IMAN|é©¬æ©å²›|Mann)", emoji: "ğŸ‡®ğŸ‡²" }
    - { match: "(India|Mumbai|å°åº¦|å­Ÿä¹°)", emoji: "ğŸ‡®ğŸ‡³" }
    - { match: "(ä¼Šæœ—|Iran)", emoji: "ğŸ‡®ğŸ‡·" }
    - { match: "(Iceland|å†°å²›)", emoji: "ğŸ‡®ğŸ‡¸" }
    - { match: "(Italy|Milan|æ„å¤§åˆ©|ç±³å…°)", emoji: "ğŸ‡®ğŸ‡¹" }
    - { match: "(çº¦æ—¦|Jordan)", emoji: "ğŸ‡¯ğŸ‡´" }
    - { match: "(è‚¯å°¼äºš|Kenya)", emoji: "ğŸ‡°ğŸ‡ª" }
    - { match: "(å‰å°”å‰æ–¯æ–¯å¦|Kyrgyzstan)", emoji: "ğŸ‡°ğŸ‡¬" }
    - { match: "(æŸ¬åŸ”å¯¨|Cambodia)", emoji: "ğŸ‡°ğŸ‡­" }
    - { match: "(KP|North.*?Korea|æœé²œ)", emoji: "ğŸ‡°ğŸ‡µ" }
    - { match: "(å“ˆè¨å…‹æ–¯å¦|Kazakhstan)", emoji: "ğŸ‡°ğŸ‡¿" }
    - { match: "(ç«‹é™¶å®›|Lietuvos)", emoji: "ğŸ‡±ğŸ‡¹" }
    - { match: "(å¢æ£®å ¡|Luxemburg|Luxembourg)", emoji: "ğŸ‡±ğŸ‡º" }
    - { match: "(æ‹‰è„±ç»´äºš|Latvia)", emoji: "ğŸ‡±ğŸ‡»" }
    - { match: "(Moldova|æ‘©å°”å¤šç“¦)", emoji: "ğŸ‡²ğŸ‡©" }
    - { match: "(åŒ—é©¬å…¶é¡¿|Macedonia)", emoji: "ğŸ‡²ğŸ‡°" }
    - { match: "(è’™å¤|ĞœĞ¾Ğ½Ğ³Ğ¾Ğ»ÑƒĞ»Ñ|Mongolia)", emoji: "ğŸ‡²ğŸ‡³" }
    - { match: "(MO|Macao|æ¾³.*(?!â–·|å›|è½¬)|CTM)", emoji: "ğŸ‡²ğŸ‡´" }
    - { match: "(å¢¨è¥¿å“¥|Mexico)", emoji: "ğŸ‡²ğŸ‡½" }
    - { match: "(MY|Malaysia|é©¬æ¥è¥¿äºš)", emoji: "ğŸ‡²ğŸ‡¾" }
    - { match: "(å°¼æ—¥åˆ©äºš|Nigeria)", emoji: "ğŸ‡³ğŸ‡¬" }
    - { match: "(NL|Netherlands|è·å…°|é˜¿å§†æ–¯ç‰¹ä¸¹)", emoji: "ğŸ‡³ğŸ‡±" }
    - { match: "(Norway|æŒªå¨)", emoji: "ğŸ‡³ğŸ‡´" }
    - { match: "(æ–°è¥¿å…°|çº½è¥¿å…°)", emoji: "ğŸ‡³ğŸ‡¿" }
    - { match: "(å·´æ‹¿é©¬|Panama)", emoji: "ğŸ‡µğŸ‡¦" }
    - { match: "(ç§˜é²|Peru)", emoji: "ğŸ‡µğŸ‡ª" }
    - { match: "(PH|Philippines|è²å¾‹å®¾)", emoji: "ğŸ‡µğŸ‡­" }
    - { match: "(Pakistan|å·´åŸºæ–¯å¦)", emoji: "ğŸ‡µğŸ‡°" }
    - { match: "(Poland|æ³¢å…°)", emoji: "ğŸ‡µğŸ‡±" }
    - { match: "(è‘¡è„ç‰™|Portugal)", emoji: "ğŸ‡µğŸ‡¹" }
    - { match: "(RO|Romania|ç½—é©¬å°¼äºš)", emoji: "ğŸ‡·ğŸ‡´" }
    - { match: "(å¡å°”ç»´äºš|Serbia)", emoji: "ğŸ‡·ğŸ‡¸" }
    - { match: "(SA|Arabia|æ²™ç‰¹)", emoji: "ğŸ‡¸ğŸ‡¦" }
    - { match: "(SE|Sweden|ç‘å…¸)", emoji: "ğŸ‡¸ğŸ‡ª" }
    - { match: "(æ–¯æ´›æ–‡å°¼äºš|Slovenia)", emoji: "ğŸ‡¸ğŸ‡®" }
    - { match: "(æ–¯æ´›ä¼å…‹|Slovensko)", emoji: "ğŸ‡¸ğŸ‡°" }
    - { match: "(TH|Thailand|æ³°å›½|æ›¼è°·)", emoji: "ğŸ‡¹ğŸ‡­" }
    - { match: "(çªå°¼æ–¯|Tunisia)", emoji: "ğŸ‡¹ğŸ‡³" }
    - { match: "(TR|Turkey|åœŸè€³å…¶|åœŸ.*(?!â–·|å›|è½¬)|ä¼Šæ–¯å¦å¸ƒå°”)", emoji: "ğŸ‡¹ğŸ‡·" }
    - { match: "(ä¹Œæ‹‰åœ­|Uruguay)", emoji: "ğŸ‡ºğŸ‡¾" }
    - { match: "(VN|Vietnam|è¶Šå—)", emoji: "ğŸ‡»ğŸ‡³" }
    - { match: "(ZA|Africa|å—é)", emoji: "ğŸ‡¿ğŸ‡¦" }
    - {
        match: "(?i:UK|England|United.*?Kingdom|London|è‹±.*(?!â–·|å›|è½¬)|[^-]è‹±|ä¼¦æ•¦)",
        emoji: "ğŸ‡¬ğŸ‡§",
      }
    - {
        match: "(?i:JP|Japan|Tokyo|Osaka|Saitama|æ—¥.*(?!â–·|å›|è½¬)|ä¸œäº¬|å¤§é˜ª|åŸ¼ç‰|æ²ªæ—¥|ç©—æ—¥|å·æ—¥|ä¸­æ—¥|æ³‰æ—¥|æ­æ—¥|[^-]æ—¥)",
        emoji: "ğŸ‡¯ğŸ‡µ",
      }
    - { match: "(?i:KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“)", emoji: "ğŸ‡°ğŸ‡·" }
    - {
        match: "(?i:RU|Russia|Moscow|Petersburg|Siberia|ä¿„.*(?!â–·|å›|è½¬)|ä¼¯åŠ›|è«æ–¯ç§‘|åœ£å½¼å¾—å ¡|è¥¿ä¼¯åˆ©äºš|æ–°è¥¿ä¼¯åˆ©äºš|å“ˆå·´ç½—å¤«æ–¯å…‹|ä¿„ç½—æ–¯|äº¬ä¿„|æ­ä¿„|[^-]ä¿„)",
        emoji: "ğŸ‡·ğŸ‡º",
      }
    - {
        match: "(?i:SG|æ–°åŠ å¡|æ–°(?!â–·|è¥¿)|Singapore|ç‹®åŸ|æ²ªæ–°|äº¬æ–°|æ³‰æ–°|ç©—æ–°|æ·±æ–°|æ­æ–°|[^-]æ–°)",
        emoji: "ğŸ‡¸ğŸ‡¬",
      }
    - {
        match: "(?i:US|America|United.*?States|ç¾.*(?!â–·|å›|è½¬)|[^-]ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|æ²ªç¾|äº¬ç¾)",
        emoji: "ğŸ‡ºğŸ‡¸",
      }
    - {
        match: "(?i:HK|Hong.*?Kong|HKT|HKBN|HGC|WTT|CMI|æ¸¯(?!â–·|å›|è½¬)|[^-]æ¸¯)",
        emoji: "ğŸ‡­ğŸ‡°",
      }
    - {
        match: "(?i:TW|Taiwan|CHT|HiNet|å°.*(?!â–·|å›|è½¬)|å°åŒ—|å°ä¸­|æ–°åŒ—|å½°åŒ–|[^-]å°)",
        emoji: "ğŸ‡¹ğŸ‡¼",
      }
    - {
        match: "(?i:CN|China|å›å›½|ä¸­.*(?!â–·|å›|è½¬)|è‹.*(?!â–·|å›|è½¬)|äº¬.*(?!â–·|å›|è½¬)|æ²ª.*(?!â–·|å›|è½¬)|ç©—.*(?!â–·|å›|è½¬)|æ·±(?!â–·|æ¸¯)|æ­.*(?!â–·|å›|è½¬)|å¾.*(?!â–·|å›|è½¬)|é’.*(?!â–·|å›|è½¬)|ç”¬.*(?!â–·|å›|è½¬)|é•‡.*(?!â–·|å›|è½¬)|ç¦….*(?!â–·|å›|è½¬)|è“‰.*(?!â–·|å›|è½¬)|æ±Ÿè‹|åŒ—äº¬|ä¸Šæµ·|å¹¿å·|æ·±åœ³|æ­å·|å¸¸å·|å¾å·|é’å²›|å®æ³¢|é•‡æ±Ÿ|æˆéƒ½|back)",
        emoji: "ğŸ‡¨ğŸ‡³",
      }

template_args:
  - { key: clash.mixed_port, value: 8888 }
  - { key: clash.redir_port, value: 8890 }
  - { key: clash.allow_lan, value: false }
  - { key: clash.log_level, value: silent }
  - { key: clash.ipv6, value: true }
  - { key: clash.api_port, value: 0.0.0.0:8080 }
